### ISSUE TITLE
Flat rate shows USD instead of the currency selected in the general settings

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-product-rates#12]
![kwi25k](https://user-images.githubusercontent.com/4752949/31550135-9c0c900c-b030-11e7-9bdd-ae37f52bd31e.png)

Ticket: https://secure.helpscout.net/conversation/446818500/68283?folderId=205529.

**Comment by michaelbeil** [comment]
Another user is experiencing this: https://secure.helpscout.net/conversation/538905987/77879?folderId=205524.
<img width="1112" alt="screen-shot-2018-03-10-at-1 28 49-pm" src="https://user-images.githubusercontent.com/4752949/37252871-8ca2fc5a-2529-11e8-92ac-3fca2c93a357.png">

**Comment by michaelbeil** [comment]
Another user is experiencing this: https://secure.helpscout.net/conversation/541923818/78211/.

![affiliate wp product rates](https://user-images.githubusercontent.com/4752949/37471036-2af94994-2869-11e8-8b14-840eff098d44.png)

**Comment by michaelbeil** [comment]
Another user is experiencing this: https://secure.helpscout.net/conversation/674356437/91161?folderId=205524.

**Comment by tubiz** [comment]
> This PR fixes the issue for General product rates, but not for recurring product rates:
> 
> ![k4blzh](https://user-images.githubusercontent.com/4752949/46246831-be36ab80-c403-11e8-92b8-952bd6cef51c.gif)

@michaelbeil another issue will have to be created on the Recurring Referrals repo for this.

**Comment by gspice** [comment]
@tubiz  I am testing with this branch /12 and it correctly shows the rate type as Flat EUR in my case.  However, when it creates the referral, it is dropping the decimal.  

Using currency `Euros`, Thousands Separator . and Decimal Separator , a flat rate referral for `16,50` is creating a referral for `16,00`.

<img width="1048" alt="wc-product-rates" src="https://user-images.githubusercontent.com/3018245/47320978-efbc2480-d607-11e8-876f-ae5bb74945e8.png">

<img width="1014" alt="screen shot 2018-10-22 at 14 37 14" src="https://user-images.githubusercontent.com/3018245/47320986-fc407d00-d607-11e8-9764-8d793ee8f256.png">

Reported today from this HS ticket:
https://secure.helpscout.net/conversation/690555334/92611?folderId=1170842

**Comment by tubiz** [comment]
> @tubiz I am testing with this branch /12 and it correctly shows the rate type as Flat EUR in my case. However, when it creates the referral, it is dropping the decimal.
> 
> Using currency `Euros`, Thousands Separator . and Decimal Separator , a flat rate referral for `16,50` is creating a referral for `16,00`.
> 
> <img alt="wc-product-rates" width="1048" src="https://user-images.githubusercontent.com/3018245/47320978-efbc2480-d607-11e8-876f-ae5bb74945e8.png">
> 
> <img alt="screen shot 2018-10-22 at 14 37 14" width="1014" src="https://user-images.githubusercontent.com/3018245/47320986-fc407d00-d607-11e8-9764-8d793ee8f256.png">
> 
> Reported today from this HS ticket:
> https://secure.helpscout.net/conversation/690555334/92611?folderId=1170842

@gspice the product rate has to be entered using a decimal point as the decimal separator. The decimal seperator settings option is used to display a referral amount and for other numbers that contains a decimal.

**Comment by gspice** [comment]
@tubiz OK, thank you.  I'll need to update the documentation for this since that is not obvious IMO.

**Comment by michaelbeil** [comment]
Reopening ... I just realized that the PR for this has not been merged.

**Comment by gspice** [comment]
Had another report of this, can we get this update released since the fix has already been done ? 
https://secure.helpscout.net/conversation/811106270/103585?folderId=205524
