### ISSUE TITLE
Add Spanish translation files

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-product-rates#13]
A user sent us some Spanish translation files to be added in a future version.

Ticket: https://secure.helpscout.net/conversation/623661841/86262?folderId=634609

**Comment by amdrew** [comment]
Translations are handled by wp.org https://translate.wordpress.org/projects/wp-plugins/affiliatewp-affiliate-product-rates

**Comment by michaelbeil** [comment]
This will be handled in https://github.com/AffiliateWP/affiliatewp-affiliate-product-rates/issues/19.
