### ISSUE TITLE
Allow language translations to be handled by WP repo

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-product-rates#19]
We need to update this plugin so the language files are handled by the WP repo. Similar to: easydigitaldownloads/edd-featured-downloads#9

**Comment by DrewAPicture** [comment]
Note: Ask @DrewAPicture about how to best accomplish this.

**Comment by dbeja** [comment]
PR: #37

**Comment by dbeja** [comment]
Merged #37 against `release/1.1`.
