### ISSUE TITLE
Product rate cannot be added 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-product-rates#24]
Two customers are experiencing an issue where they cannot add a product rate to an affiliate using Affiliate Product Rates 1.0.5. I could not replicate the issue on our testing site with AffiliateWP 2.2.16 and Affiliate Product Rates 1.0.5. 

On both customer sites I was experiencing a 404 error which was causing our assets not to load, but then I installed Affiliate Product Rates 1.0.4 and this fixed the issue.  

This is what is happening with Affiliate Product Rates 1.0.5 installed on the customers sites':
![Screen Capture on 2019-04-26 at 22-46-06](https://user-images.githubusercontent.com/4752949/56835707-49caca80-6875-11e9-8201-e52694939afe.gif)
 
This is the 404 error:
`Failed to load resource: the server responded with a status of 404 () - /wp-content/plugins/affiliatewp-affiliate-product-rates/assets/css/select2.min.css?ver=1.0.5`

This is what is supposed to occur, which can be seen with Affiliate Product Rates 1.0.4 installed on the customers sites', which does not show the 404 error:

![Screen Capture on 2019-04-26 at 22-23-54](https://user-images.githubusercontent.com/4752949/56835266-fad06580-6873-11e9-93f0-e96b9e5fbf85.gif) 

Tickets: https://secure.helpscout.net/conversation/835771150/118789?folderId=634609, https://secure.helpscout.net/conversation/837658398/118943/?folderId=634609.

**Comment by DrewAPicture** [comment]
I poked around a little bit and didn't see anything that would directly cause this problem in 1.0.5 vs 1.0.4. I was hoping to login to one or both of the customer sites to take a look but couldn't get into either of them either.

**Comment by michaelbeil** [comment]
Added a note with login credentials to the top of each ticket to help you look into this.

**Comment by michaelbeil** [comment]
I have now been able to replicate the issue after deactivating all other plugins except AffiliateWP v2.2.16, Affiliate Product Rates v1.0.5, and WooCommerce v3.6.2. I also activated the Twenty Nineteen theme v1.3, using WordPress 5.1.1, PHP v5.5.38 all the way up to PHP 7.3, and MySQL v5.6.40. The issue appears to be coming from the MySQL version, as I do not experience this on another site with MySQL 5.6.10.

**Comment by michaelbeil** [comment]
@DrewAPicture @alexstandiford Do you guys experience the same issue?

**Comment by michaelbeil** [comment]
On a site using AffiliateWP 2.2.16, Affiliate Product Rates 1.0.5, WooCommerce 3.6.2, the default WordPress Twenty Nineteen theme 1.3, WordPress 5.1.1, PHP 7.3, and MySQL 5.6.40, I was able to replicate the issue. 

@DrewAPicture @alexstandiford If you use MySQL 5.6.40, are you able to replicate the issue?

**Comment by tubiz** [comment]
A new ticket https://secure.helpscout.net/conversation/846106877/119761?folderId=205524 was just submitted by another customer regarding this issue.

While checking I noticed that the minified `select2.min.css` CSS file is not in the latest version `1.0.5` on https://wordpress.org/plugins/affiliatewp-affiliate-product-rates

**Comment by DrewAPicture** [comment]
@tubiz Oof, that would probably do it.

**Comment by DrewAPicture** [comment]
Probably the reason why I wasn't seeing the problem locally is that I have `SCRIPT_DEBUG` enabled. Crap.

Stuff like this sometimes exposes flaws in the testing process and reminds you to think like the end-user in all aspects, even ones that seem obvious but are still forgotten. Nice catch!

**Comment by tubiz** [comment]
@DrewAPicture version `1.0.6` can be released as the minified `select2.min.css` file is already on GitHub https://github.com/AffiliateWP/affiliatewp-affiliate-product-rates/blob/master/assets/css/select2.min.css

**Comment by DrewAPicture** [comment]
OK @tubiz, I'll take care of it.

**Comment by DrewAPicture** [comment]
v1.0.5.1 has been released on .org.
